apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: finch
type: Opaque
stringData:
  POSTGRES_DB: bmidb
  POSTGRES_USER: bmi_user
  POSTGRES_PASSWORD: strongpassword
  DATABASE_URL: postgresql://bmi_user:strongpassword@postgresql.finch.svc.cluster.local:5432/bmidb
