apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finch-ingress
  namespace: finch
spec:
  ingressClassName: nginx
  rules:
    - host: finch.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
