loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem

singleBinary:
  replicas: 1

monitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true

grafana:
  enabled: false
