grafana:
  adminPassword: admin123
  defaultDashboardsTimezone: browser
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

prometheus:
  prometheusSpec:
    retention: 10d
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
