apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: finch
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - finch
  endpoints:
    - port: http
      path: /healthz
      interval: 30s
