apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: finch
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - finch
  endpoints:
    - port: http
      path: /health
      interval: 30s
